/**
 * Scaffold `.fieldnote/profile.md` by READING the repository.
 *
 * Every value written here traces to something observed: a package.json
 * script, a label the tracker actually has, a file that exists, a branch
 * protection setting the API returned. What cannot be observed is written
 * as TODO. Guessing would make the profile untrustworthy, and the profile is
 * what the skills — and later fieldnote's Act arm — build on.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { findGitRoot } from "../paths.js";
import type { Env } from "../types.js";
import { UserError } from "../types.js";

export interface ProbeResult {
  scripts: Record<string, string>;
  labels: string[];
  docs: string[];
  strictStatusChecks: boolean | null;
  tracker: { kind: string | null; repo: string | null };
  hasPlansDir: boolean;
  git: { baseRemote: string | null; baseBranch: string | null };
}

const TODO = "TODO";

/** First script name present in `scripts`, else null. */
function pickScript(scripts: Record<string, string>, candidates: string[]): string | null {
  for (const name of candidates) {
    if (Object.prototype.hasOwnProperty.call(scripts, name)) return `npm run ${name}`;
  }
  return null;
}

/** First label matching any pattern, else null. */
function pickLabel(labels: string[], patterns: RegExp[]): string | null {
  for (const re of patterns) {
    const hit = labels.find((l) => re.test(l));
    if (hit) return hit;
  }
  return null;
}

/** First doc path whose basename matches, else null. */
function pickDoc(docs: string[], re: RegExp): string | null {
  return docs.find((d) => re.test(d)) ?? null;
}

export function renderProfile(probe: ProbeResult): string {
  const trackerKind = probe.tracker.kind ?? TODO;
  const trackerRepo = probe.tracker.repo ?? TODO;

  // "test" is deliberately excluded: a bare unit-test script is not the same
  // claim as "this repository's fast checks (lint, typecheck, unit tests)"
  // (docs/profile.md), and presenting one as the other would let a skill
  // report a passing quality gate when lint/typecheck never ran.
  const check = pickScript(probe.scripts, ["check", "verify", "ci"]) ?? TODO;
  const preflight = pickScript(probe.scripts, ["preflight", "quality:preflight", "lint"]) ?? TODO;
  const mutation = pickScript(probe.scripts, ["mutation", "mutation:changed", "stryker"]) ?? TODO;

  const ready = pickLabel(probe.labels, [/ready.*agent/i, /^ready$/i]) ?? TODO;
  // "epic" is deliberately excluded: it usually means "large feature", not
  // "needs a PRD before implementation can start".
  const needsPrd = pickLabel(probe.labels, [/prd/i]) ?? TODO;

  const dod = pickDoc(probe.docs, /definition-of-done|dod/i) ?? TODO;
  const pr = pickDoc(probe.docs, /pull-request|contributing/i) ?? TODO;
  const testing = pickDoc(probe.docs, /testing/i) ?? TODO;
  const verification = pickDoc(probe.docs, /verification/i) ?? TODO;
  const ciTriage = pickDoc(probe.docs, /ci-triage/i) ?? TODO;
  const plans = probe.hasPlansDir ? "./plans/" : TODO;
  const strict =
    probe.strictStatusChecks === null ? TODO : String(probe.strictStatusChecks);

  const baseRemote = probe.git.baseRemote ?? TODO;
  const baseBranch = probe.git.baseBranch ?? TODO;

  return `# fieldnote profile

Generated by \`fieldnote-skills init\`. Every value below was read from this
repository; anything it could not determine is marked TODO. Replace the TODOs —
a skill that meets one will stop and ask rather than guess.

This file carries FACTS, never PROCEDURE. See
https://github.com/dervalp/fieldnote-skills/blob/main/docs/profile.md

## Tracker

- **kind** — ${trackerKind}
- **repo** — ${trackerRepo}
- **epicLink** — ${TODO}
- **blockedBy** — ${TODO}

## Labels

- **ready** — ${ready}
- **needsPrd** — ${needsPrd}

## Commands

- **check** — ${check}
- **preflight** — ${preflight}
- **mutation** — ${mutation}

## Docs

- **definitionOfDone** — ${dod}
- **pullRequest** — ${pr}
- **testing** — ${testing}
- **verification** — ${verification}
- **ciTriage** — ${ciTriage}
- **plans** — ${plans}

## Architecture

- ${TODO}: one line per rule a change must respect here.

## Parallelism

- **waveSize** — ${TODO}

## Merge policy

- **strictStatusChecks** — ${strict}
- **adminMerge** — ${TODO}

## Localization

- **canonicalLocale** — ${TODO}
- **locales** — ${TODO}
- **catalogs** — ${TODO}

## Git

- **baseRemote** — ${baseRemote}
- **baseBranch** — ${baseBranch}
`;
}

function readScripts(repoRoot: string): Record<string, string> {
  const pkg = join(repoRoot, "package.json");
  if (!existsSync(pkg)) return {};
  try {
    const parsed = JSON.parse(readFileSync(pkg, "utf8")) as { scripts?: Record<string, string> };
    return parsed.scripts ?? {};
  } catch {
    return {};
  }
}

function readLabels(): string[] {
  try {
    const out = execFileSync("gh", ["label", "list", "--limit", "200", "--json", "name"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return (JSON.parse(out) as { name: string }[]).map((l) => l.name);
  } catch {
    return [];
  }
}

function readDocs(repoRoot: string): string[] {
  const found: string[] = [];
  for (const candidate of [
    "CONTRIBUTING.md",
    "AGENTS.md",
    "CLAUDE.md",
    "docs/definition-of-done.md",
    "docs/pull-request.md",
    "docs/testing.md",
    "docs/verification.md",
    "docs/ci-triage.md",
  ]) {
    if (existsSync(join(repoRoot, candidate))) found.push(candidate);
  }
  return found;
}

/** Whether a `plans/` directory exists at the repo root. */
function readPlansDir(repoRoot: string): boolean {
  return existsSync(join(repoRoot, "plans"));
}

/**
 * `owner/repo` from the `origin` git remote when it points at github.com,
 * falling back to `gh repo view` (which only ever answers for GitHub).
 * Never guesses at a non-GitHub tracker kind.
 */
function readTracker(repoRoot: string): { kind: string | null; repo: string | null } {
  try {
    const url = execFileSync("git", ["remote", "get-url", "origin"], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const match = /github\.com[:/]([^/]+\/[^/]+?)(\.git)?$/.exec(url);
    if (match) return { kind: "github", repo: match[1]! };
  } catch {
    // fall through to the gh-backed probe below
  }

  try {
    const nameWithOwner = execFileSync(
      "gh",
      ["repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"],
      { cwd: repoRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    if (nameWithOwner) return { kind: "github", repo: nameWithOwner };
  } catch {
    // no remote, an unrecognisable remote, and no usable `gh` — TODO it is
  }

  return { kind: null, repo: null };
}

/**
 * The remote a PR should be based on: `origin` when this clone has one, else
 * the sole remote if there's exactly one, else unresolved. Never guesses at
 * a fork-workflow remote name like `upstream`.
 */
function readBaseRemote(repoRoot: string): string | null {
  try {
    const out = execFileSync("git", ["remote"], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const remotes = out.length > 0 ? out.split("\n") : [];
    if (remotes.includes("origin")) return "origin";
    if (remotes.length === 1) return remotes[0]!;
    return null;
  } catch {
    return null;
  }
}

/**
 * The branch PRs target: this clone's cached remote HEAD
 * (`refs/remotes/<remote>/HEAD`, set by `git remote set-head` or a normal
 * clone), falling back to GitHub's recorded default branch. Empty/missing
 * answers (e.g. a remote with no commits yet) are treated as unresolved
 * rather than guessed at.
 */
function readBaseBranch(repoRoot: string, remote: string | null): string | null {
  if (remote) {
    try {
      const ref = execFileSync("git", ["symbolic-ref", `refs/remotes/${remote}/HEAD`], {
        cwd: repoRoot,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      const match = /\/([^/]+)$/.exec(ref);
      if (match) return match[1]!;
    } catch {
      // not cached locally — fall through to the gh-backed probe below
    }
  }

  try {
    const name = execFileSync(
      "gh",
      ["repo", "view", "--json", "defaultBranchRef", "--jq", ".defaultBranchRef.name"],
      { cwd: repoRoot, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    if (name.length > 0) return name;
  } catch {
    // no gh, or no default branch yet (e.g. an empty repository) — TODO it is
  }

  return null;
}

function readStrictChecks(): boolean | null {
  try {
    const out = execFileSync(
      "gh",
      ["api", "repos/{owner}/{repo}/branches/main/protection", "--jq", ".required_status_checks.strict"],
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    if (out === "true") return true;
    if (out === "false") return false;
    return null;
  } catch {
    return null;
  }
}

export function probeRepo(repoRoot: string): ProbeResult {
  const baseRemote = readBaseRemote(repoRoot);
  return {
    scripts: readScripts(repoRoot),
    labels: readLabels(),
    docs: readDocs(repoRoot),
    strictStatusChecks: readStrictChecks(),
    tracker: readTracker(repoRoot),
    hasPlansDir: readPlansDir(repoRoot),
    git: { baseRemote, baseBranch: readBaseBranch(repoRoot, baseRemote) },
  };
}

export async function runInit(env: Env, opts: { force?: boolean } = {}): Promise<number> {
  const cwd = process.cwd();
  const root = env.repoRoot ?? findGitRoot(cwd);
  if (root === null) {
    throw new UserError(
      `Could not find a git repository at or above ${cwd}. Run \`fieldnote-skills init\` from inside ` +
        "the repository you want to profile (or one of its subdirectories).",
    );
  }
  const dir = join(root, ".fieldnote");
  const target = join(dir, "profile.md");

  if (existsSync(target) && !opts.force) {
    throw new UserError(`${target} already exists. Pass --force to overwrite it.`);
  }

  const markdown = renderProfile(probeRepo(root));
  mkdirSync(dir, { recursive: true });
  writeFileSync(target, markdown, "utf8");

  const todos = (markdown.match(/TODO/g) ?? []).length;
  env.logger.info(`Wrote ${target}`);
  if (todos > 0) {
    env.logger.warn(`${todos} value(s) could not be read from this repository — marked TODO.`);
  }
  return 0;
}
