/**
 * Scaffold `.fieldnote/profile.md` by READING the repository.
 *
 * Every value written here traces to something observed: a package.json
 * script, a label the tracker actually has, a file that exists, a branch
 * protection setting the API returned. What cannot be observed is written
 * as TODO. Guessing would make the profile untrustworthy, and the profile is
 * what the skills — and later fieldnote's Act arm — build on.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Env } from "../types.js";
import { UserError } from "../types.js";

export interface ProbeResult {
  scripts: Record<string, string>;
  labels: string[];
  docs: string[];
  strictStatusChecks: boolean | null;
}

const TODO = "TODO";

/** First script name present in `scripts`, else null. */
function pickScript(scripts: Record<string, string>, candidates: string[]): string | null {
  for (const name of candidates) {
    if (Object.prototype.hasOwnProperty.call(scripts, name)) return `npm run ${name}`;
  }
  return null;
}

/** First label matching any pattern, else null. */
function pickLabel(labels: string[], patterns: RegExp[]): string | null {
  for (const re of patterns) {
    const hit = labels.find((l) => re.test(l));
    if (hit) return hit;
  }
  return null;
}

/** First doc path whose basename matches, else null. */
function pickDoc(docs: string[], re: RegExp): string | null {
  return docs.find((d) => re.test(d)) ?? null;
}

export function renderProfile(probe: ProbeResult): string {
  const check = pickScript(probe.scripts, ["check", "verify", "ci", "test"]) ?? TODO;
  const preflight = pickScript(probe.scripts, ["preflight", "quality:preflight", "lint"]) ?? TODO;
  const mutation = pickScript(probe.scripts, ["mutation", "mutation:changed", "stryker"]) ?? TODO;

  const ready = pickLabel(probe.labels, [/ready.*agent/i, /^ready$/i]) ?? TODO;
  const needsPrd = pickLabel(probe.labels, [/prd/i, /^epic$/i]) ?? TODO;

  const dod = pickDoc(probe.docs, /definition-of-done|dod/i) ?? TODO;
  const pr = pickDoc(probe.docs, /pull-request|contributing/i) ?? TODO;
  const testing = pickDoc(probe.docs, /testing/i) ?? TODO;
  const strict =
    probe.strictStatusChecks === null ? TODO : String(probe.strictStatusChecks);

  return `# fieldnote profile

Generated by \`fieldnote-skills init\`. Every value below was read from this
repository; anything it could not determine is marked TODO. Replace the TODOs —
a skill that meets one will stop and ask rather than guess.

This file carries FACTS, never PROCEDURE. See
https://github.com/dervalp/fieldnote-skills/blob/main/docs/profile.md

## Labels

- **ready** — ${ready}
- **needsPrd** — ${needsPrd}

## Commands

- **check** — ${check}
- **preflight** — ${preflight}
- **mutation** — ${mutation}

## Docs

- **definitionOfDone** — ${dod}
- **pullRequest** — ${pr}
- **testing** — ${testing}
- **plans** — ./plans/

## Architecture

- ${TODO}: one line per rule a change must respect here.

## Parallelism

- **waveSize** — 4

## Merge policy

- **strictStatusChecks** — ${strict}
- **adminMerge** — ${TODO}
`;
}

function readScripts(repoRoot: string): Record<string, string> {
  const pkg = join(repoRoot, "package.json");
  if (!existsSync(pkg)) return {};
  try {
    const parsed = JSON.parse(readFileSync(pkg, "utf8")) as { scripts?: Record<string, string> };
    return parsed.scripts ?? {};
  } catch {
    return {};
  }
}

function readLabels(): string[] {
  try {
    const out = execFileSync("gh", ["label", "list", "--limit", "200", "--json", "name"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return (JSON.parse(out) as { name: string }[]).map((l) => l.name);
  } catch {
    return [];
  }
}

function readDocs(repoRoot: string): string[] {
  const found: string[] = [];
  for (const candidate of [
    "CONTRIBUTING.md",
    "AGENTS.md",
    "CLAUDE.md",
    "docs/definition-of-done.md",
    "docs/pull-request.md",
    "docs/testing.md",
    "docs/ci-triage.md",
  ]) {
    if (existsSync(join(repoRoot, candidate))) found.push(candidate);
  }
  return found;
}

function readStrictChecks(): boolean | null {
  try {
    const out = execFileSync(
      "gh",
      ["api", "repos/{owner}/{repo}/branches/main/protection", "--jq", ".required_status_checks.strict"],
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    ).trim();
    if (out === "true") return true;
    if (out === "false") return false;
    return null;
  } catch {
    return null;
  }
}

export function probeRepo(repoRoot: string): ProbeResult {
  return {
    scripts: readScripts(repoRoot),
    labels: readLabels(),
    docs: readDocs(repoRoot),
    strictStatusChecks: readStrictChecks(),
  };
}

export async function runInit(env: Env, opts: { force?: boolean } = {}): Promise<number> {
  const root = env.repoRoot ?? process.cwd();
  const dir = join(root, ".fieldnote");
  const target = join(dir, "profile.md");

  if (existsSync(target) && !opts.force) {
    throw new UserError(`${target} already exists. Pass --force to overwrite it.`);
  }

  const markdown = renderProfile(probeRepo(root));
  mkdirSync(dir, { recursive: true });
  writeFileSync(target, markdown, "utf8");

  const todos = (markdown.match(/TODO/g) ?? []).length;
  env.logger.info(`Wrote ${target}`);
  if (todos > 0) {
    env.logger.warn(`${todos} value(s) could not be read from this repository — marked TODO.`);
  }
  return 0;
}
